

# api-training
# dev-api-training      - k8s
# workjam-api-training  - gcr

# router
# dev-workjam-router
# workjam-router



registry: us.gcr.io
# repository: workjam-infra/workjam/workjam-
repository: workjam-infra/workjam/workjam-

# k8s:
#   prefix: workjam-

statefulsets:
    - api-core

# kdeploy router -k         workjam-router 
# kdeploy router --k8s-name workjam-router 